package li.gkd.app.subscription

/** Business failures retain their identity and diagnostic cause until the display boundary. */
class SubscriptionException(
    val reason: SubscriptionFailureReason,
    val arguments: List<String> = emptyList(),
    cause: Throwable? = null,
) : IllegalStateException(
    reason.name + if (arguments.isEmpty()) "" else arguments.joinToString(prefix = ": "),
    cause,
)

enum class SubscriptionFailureReason {
    CategoryConfigConflict,
    CategoryKeyExhausted,
    CategoryMissing,
    CategoryNameDuplicate,
    CategoryNameRequired,
    ExclusionConfigConflict,
    FileDeleteFailed,
    FormatInvalidDetail,
    PageExclusionConflict,
    RemoteCategoryDeleteUnsupported,
    RemoteCategoryEditUnsupported,
    RuleAppIdMismatch,
    RuleEditConflict,
    RuleIdRequired,
    RuleInputRequired,
    RuleInvalidDetail,
    RuleInvalidPosition,
    RuleKeyMismatch,
    RuleMissing,
    RuleMissingKey,
    RuleNameDuplicate,
    RuleObjectRequired,
    RuleSwitchConflict,
    SelectedRulesMissing,
    SelectorInvalidDetail,
    SubscriptionAppMissing,
    SubscriptionContentConflict,
    SubscriptionFileIdMismatch,
    SubscriptionFileMissing,
    SubscriptionFileParseFailed,
    SubscriptionIdImmutable,
    SubscriptionItemIdMismatch,
    SubscriptionMissing,
    SubscriptionMissingId,
    SubscriptionNotLoaded,
    SubscriptionNotLoadedId,
    SubscriptionPreviewConflict,
    SubscriptionUnloadedOrMissing,
    SubscriptionUpdateUrlRequestFailed,
    SubscriptionUpdatedIdMismatch,
    TextParseFailed,
}
