name: Bug report
title: "[BUG] "
description: Report the bug you encountered
labels: ["pending triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for taking the time to fill this out. Before submitting, please make sure you have:
        1. Please **ensure** you have read the [GKD official documentation](https://gkd.li) and the [FAQ](https://gkd.li/guide/faq)
        2. Please **determine** if it is a third-party rule subscription issue. If so, you should feedback to the rule provider instead of submitting here. **Only issues with the GKD app itself are accepted here.**
        3. Please **ensure** no one has submitted a similar issue in the existing [issues](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) or [discussions](https://github.com/orgs/gkd-kit/discussions?discussions_q=). Otherwise, please discuss under that issue
        4. Please **ensure** your issue can be reproduced on the latest version released in [releases](https://github.com/gkd-kit/gkd/releases/latest) (including test versions). If not, please update to the latest version and reproduce before submitting
  - type: textarea
    id: log-file
    attributes:
      label: |
        Log file
      description: |
        Home - Settings - About - Logs, upload the log file or generate a link and paste it into the input box below\
        Log files are required for any issue. Otherwise it will be closed directly. Please do not just send text/screenshots/videos
    validations:
      required: true
  - type: textarea
    id: bug-1
    attributes:
      label: |
        Bug description (text/screenshot/video)
      description: |
        Please use as accurate a description as possible, otherwise your issue will be closed directly\
        Also, if your issue is about snapshots/selectors, you must provide a snapshot link or snapshot file, otherwise your issue will be closed directly
    validations:
      required: true
  - type: textarea
    id: bug-2
    attributes:
      label: |
        Expected behavior (text/screenshot/video)
      description: |
        Please use as accurate a description as possible, otherwise your issue will be closed directly
    validations:
      required: true
  - type: textarea
    id: bug-3
    attributes:
      label: |
        Actual behavior (text/screenshot/video)
      description: |
        Please use as accurate a description as possible, otherwise your issue will be closed directly
    validations:
      required: true
