blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/gkd-kit/gkd/discussions
    about: 'Other questions or requests: selectors/rules/snapshots/accessibility/device related issues. If not found in issues, search discussions'
