name: Feature request
title: "[Feature] "
description: Propose your feature request
labels: ["pending triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for taking the time to fill this out. Before submitting, please make sure you have:
        1. GKD does not provide any rules by default. You can write your own rules or import remote subscriptions after reviewing the [GKD official documentation](https://gkd.li). Please do not ask about wanting specific rules like "I want XXX rule"
        2. Please **determine** if it is a third-party rule subscription feature request. If so, you should feedback to the rule provider instead of submitting here. **Only feature requests for the GKD app itself are accepted here.**
        3. Please **ensure** no one has submitted a similar issue in the existing [issues](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) or [discussions](https://github.com/orgs/gkd-kit/discussions?discussions_q=). Otherwise, please discuss under that issue
        4. Please **ensure** the feature you want is not available in the latest version released in [releases](https://github.com/gkd-kit/gkd/releases/latest) (including test versions). If not, please update to the latest version to verify before submitting
  - type: textarea
    id: feature-description
    attributes:
      label: |
        New feature description
      description: |
        For example: what feature you want to add to which page in GKD, and what the feature does\
        Or adding a certain field to the rule definition, and what the field does\
        Please use accurate descriptions, otherwise your issue will be closed directly
    validations:
      required: true
