name: Build-Debug-Apk

on:
  workflow_dispatch:
  push:
    branches:
      - feat/button-snapshot-download

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: "21"

      - uses: gradle/actions/setup-gradle@v5

      - run: chmod 777 ./gradlew
      - run: ./gradlew app:assembleGkdDebug

      - uses: actions/upload-artifact@v7
        with:
          name: gkd-debug-apk
          path: app/build/outputs/apk/gkd/debug/*.apk
          if-no-files-found: error
